# Generated by Django 5.1 on 2024-08-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('recipename', models.CharField(max_length=255)),
                ('majoringredients', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
    ]
