# Generated by Django 5.1 on 2024-08-23 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_remove_recipe_author_id_alter_recipe_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipes',
            unique_together={('user', 'savedrecipe')},
        ),
    ]
