# Generated by Django 5.1 on 2024-08-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_alter_savedrecipes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipes',
            unique_together=set(),
        ),
    ]
